function Bs= get_Bs(uM,thetaM,uS,thetaS,M,G)
%   Get the magnetic field at the sensor generated by the permanent magnet.
%   uM, thetaM: Pose of the permanent magnet in the global (camera) coordinate frame.
%   uS, thetaS Pose of the sensor in the global (camera) coordinate frame.
%   M, Magnetic moment
%   G，Geomagnetism
if nargin<6
    M = 1.100186666058454e+12;
end
if nargin<5
    G = zeros(3,1);
end
RSM = Exp(-thetaS)*Exp(thetaM);
RMO = Exp(-thetaM);
L = (20.8*3)/2;
R = 68/2;

r = RMO*(uS-uM);%单位mm
Bs = RSM*magField(r,M,R,L)+G;
end

